### PR TITLE
add dropdown to housing recovery plot

### PR DESCRIPTION
**Pull request by Rashmil-1999**
I added a dropdown to the housing recovery bar chart.

### CODE REVIEW

**Comment by jonglee1** [comment]
I got this error:

> ModuleNotFoundError: No module named 'ipympl'

**Comment by jonglee1** [comment]
@Rashmil-1999 Please add "ipympl" module to environment.yml and requirements.txt

**Comment by Rashmil-1999** [comment]
Done, I have added it to requirements

**Comment by navarroc** [comment]
I see %matplotlib widget. Did something not work correctly or is that expected?

Screenshot from 2024-06-03 12-07-05

**Comment by Rashmil-1999** [comment]
Yeah, we need widget for interactive plot but that messes up the other viz. so I placed these vals such that after inlines are rendered, the backend is set to widget again for the interactive plot to work

**Review by navarroc — APPROVED** [review]

**Review by longshuicy — APPROVED** [review]

**Review by ywkim312 — APPROVED** [review]

**Pull request merged**
